export const SET_USER = "SET_USER"

export const LOGIN_REQUESTED = "LOGIN_REQUESTED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const USERNAME_REQUESTED = "USERNAME_REQUESTED"
export const USERNAME_SUCCESS = "USERNAME_SUCCESS"
export const USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
export const USERNAME_ERROR = "USERNAME_ERROR"

export const SIGN_UP_REQUESTED = "SIGN_UP_REQUESTED"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"